### ISSUE TITLE
[ Feature ] A selector? For example @a, @p

### ISSUE THREAD

**Issue by Yomamaeatstoes** [HSGamer/BetterEconomy#76]
It would be cool if this plugin had a selector where you can do /eco pay @a or @p

**Comment by HSGamer** [comment]
I won't implement this because
1. Selector doesn't exist in the Spigot API. Some plugin did have selectors in their commands, but it was either hacky with NMS, complicated with logic code, or bloated with a huge library.
2. I have to implement multiple target players in these eco commands, so it defeats the current logic code.
3. If I implement this, somebody will request more selectors, which is against the goal of being simple & lightweight.

Someone will do this eventually if they want to, but I think it's less likely because of the user experience they have with other economy plugins.
